In [6]:
import pandas as pd
df=pd.read_csv("Advertising.csv")
df=df.iloc[:,1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [7]:
X=df.drop("sales",axis=1) #bağımsız değişkenler X e atandı
y=df[["sales"]] #bağımlı değişken - pandas dataframe olarak almak için [[]]

In [8]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [9]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [11]:
#StatsModels ile model kurmak

In [15]:
import statsmodels.api as sm

In [17]:
linearModel=sm.OLS(y,X) # model nesnesini oluşturduk OLS(bağımlıdeğişkeb,bağımsızdeğişken)

In [18]:
model=linearModel.fit()

In [21]:
model.summary() #model çıktısının özetti

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Sun, 11 Aug 2024   Prob (F-statistic):                   2.43e-171
Time:                        23:23:24   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [30]:
#scikitlearn ile model kurmak
from sklearn.linear_model import LinearRegression
lm=LinearRegression()

In [32]:
model=lm.fit(X,y)

In [33]:
model.intercept_

array([2.93888937])

In [34]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

Katsayılar değişti bunun sebebi ilgili modellerdeki fonksiyonların parametre tahmin yöntemlerinden kaynaklıdır

### Tahmin 
Sales = 2.94 + TV * 0.04 + radio * 0.19 - newspaper* 0.001

30 birim TV ,10 birim radio , 40 birim gazete harcaması ne kadardır?

In [39]:
2.94 + 30 * 0.04 + 10 * 0.19 -40* 0.001

5.999999999999999

In [40]:
yeni_veri=[[30],[10],[40]]

In [41]:
import pandas as pd
yeni_veri=pd.DataFrame(yeni_veri).T

In [42]:
yeni_veri

0   1   2
0  30  10  40

In [43]:
model.predict(yeni_veri)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.15562918]])

In [50]:
yeni_veri1=[[100],[200],[300]]
yeni_veri1=pd.DataFrame(yeni_veri1).T

In [51]:
model.predict(yeni_veri1)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[44.91010939]])

#### Model Başarısını Değerlendirme

In [52]:
from sklearn.metrics import mean_squared_error

In [54]:
y.head() #gerçek değerler

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [56]:
model.predict(X)[0:20] #tahmin edilen değerler

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872],
       [ 7.0322992 ],
       [17.28512918],
       [10.57712073],
       [ 8.82630048],
       [18.43436638],
       [20.81929952],
       [12.82365674],
       [23.22495716],
       [ 9.95168206],
       [14.16607293]])

In [58]:
#mean_squared_error(gerçek değerler , tahmin edilen değerler)
MSE=mean_squared_error(y,model.predict(X)) #Hata kareler ortalaması

In [59]:
MSE

2.784126314510936

In [61]:
import numpy as np
#RMSE hata kareler ortalamsının karekökü
RMSE=np.sqrt(mean_squared_error(y,model.predict(X)))
RMSE

1.6685701407225697